controllers-films-users
iwfua/java-filmorate pull request #6
Opened 2024-06-02 13:40 UTC by iwfua

2024-06-02 16:50 UTC, YazykovMikhail requested changes

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Long, Film> films = new HashMap<>();
final - ведь релизация не будет меняться во время выполнения программы

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Long, Film> films = new HashMap<>();
Касается и User

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate DATE_RELEASE = LocalDate.of(1895, 12, 28);
Статические переменные обьявляются первыми в классе

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
Стандартный шаблон для логов
createMethod(Request request) {
log.info("пришел Post запрос /films с телом: {}", request)
Response response = //логика метода, если есть бизнес процессы для логирвоания логируем их
log.info("Отправлен ответ Post /films с телом: {}", response)
}
что бы было видно что пришло, что ушло и если были какие то изменения в процессы выполнянения тоже были видны, потому что ты пойдешь в логи когда у тебя что то сломалось, просто по сообщения "Фильм добалвен" ничего не понятно.

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull @NotEmpty
@NotNull 
 @NotEmpty
 делают почти одно и тоже, но у одного из них есть дополнительаня проверка, посмотри в чем разница и оставь один
 Касается и строковых полей в User

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static void setNameIfAbsent(User user) {
статичным делать не нужно

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Long nextId() {
Получается каждый раз пробегать п овсему списку, что бы высчитать новый идентификатор, это очень сложно.
Просто сделай поле generateId
и дела ++ для него. 
Как мы делали раньше.

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Long nextId() {
Касается и Film

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@Valid @RequestBody Film film) {
Вот так будет получше:
 ```
   @PutMapping
    public Film updateFilm(@Valid @RequestBody Film film) {
        validate(film);
        Long id = film.getId();
        if (films.containsKey(id)) {
            String errorMessage = String.format("Фильм с Id=%s не найден", id);
            log.warn(errorMessage);
            throw new ValidationException(errorMessage);
        }
        films.put(id, film);
        log.info("Film с id={} успешно обновлён", id);
        return film;
    }
    
```
С учето мтого что метод validate выглядит вот так:
   ```
 private void validate(Film film) {
        if (film.getId() == null) {
            String errorMessage = "Id не указан";
            log.warn(errorMessage);
            throw new ValidationException(errorMessage);
        }

        if (film.getReleaseDate().isBefore(DATE_RELEASE)) {
            String errorMessage = "Дата релиза указана неверно";
            log.warn(errorMessage);
            throw new ValidationException(errorMessage);
        }
    }
```

2024-06-02 16:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@Valid @RequestBody Film film) {
Поправь по аналогии и для User

2024-06-03 14:26 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Long nextId() {
Исправил

2024-06-03 14:28 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@Valid @RequestBody Film film) {
Исправил 
Но так как поле id нужно только для put, а валидация releaseDate и для создания разбил проверку на два метода
Для User тоже подправил

2024-06-03 14:29 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull @NotEmpty
Понял, спасибо
Оставил @NotEmpty

2024-06-03 14:29 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
Исправил

2024-06-03 14:30 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static void setNameIfAbsent(User user) {
Исправил

2024-06-03 19:44 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull @NotEmpty
А еще лучше @NotBlank

2024-06-03 19:47 UTC, YazykovMikhail approved these changes

2024-06-03 19:47 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
Логировать нужно непосредтсвенно тот ответ, который будет возвращаен, а сейчас между логированием и ответом, может изменится состояние
 ```
      log.info("Пришел запрос GET /films);
       List<Film> films = new ArrayList<>(films.values());
       log.info("Ответ на запрос GET /films: {}, films);
       return films
```

2024-06-16 12:38 UTC, merged