add-friends-likes
iwfua/java-filmorate pull request #7
Opened 2024-06-18 12:51 UTC by iwfua

2024-06-18 18:28 UTC, YazykovMikhail requested changes

2024-06-18 18:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +
Так же стоит обрабатывать любые неизвестные ошибки:
	@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}

2024-06-18 18:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Все запросы из контроллера идут в сервис, а уже из сервиса в сторадж. 
Даже если в сервисе он ничего не делает, а просто проксирует.

2024-06-18 18:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Для UserController так же

2024-06-18 18:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty(message = "Имя не должно быть пустым")
Лучше использовать @NotBlank
посмотри в чем разница

2024-06-18 18:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Long> friendsId = new HashSet<>();
Используй 
@JsonIgnore
даные не должны использоваться в контроллерах, для работы с друзьями есть отдельные эндпоинты, тут они просто храняться

2024-06-18 18:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Long> likes = new HashSet<>();
Используй
@JsonIgnore
Даные не должны использоваться в контроллерах, для работы с лайками есть отдельные эндпоинты, тут они просто храняться

2024-06-18 18:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +
Валидации стоит вынести в сервис, нет смысла идти в ранилище, если не хватает бизнес данных. А Ббизнес данные проверяются на уровне сервиса

2024-06-18 18:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +
аналогично для User

2024-06-18 19:36 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +
Добавил

2024-06-18 19:36 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Исправил

2024-06-18 19:36 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty(message = "Имя не должно быть пустым")
Изменил, понял, @notblank не позволяет создать поле с пробелами

2024-06-18 19:36 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Long> friendsId = new HashSet<>();
Добавил

2024-06-18 19:36 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +
Исправил

2024-06-18 19:37 UTC, iwfua commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Long> likes = new HashSet<>();
Добавил

2024-06-19 05:31 UTC, YazykovMikhail approved these changes

2024-07-07 09:17 UTC, merged